Feature/ct 3
Jaonja/GitRepos pull request #12
Opened 2021-04-26 15:28 UTC by Jaonja

2021-04-27 08:11 UTC, DenisKalyanov requested changes

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +            <div class="logo-car"> <img src="img/car.png" class="car-img" alt="img"></div>
а зачем у тебя для каждого  img отдельный div?

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                <p class="textlol">Как это происходит?</p>
что за класс textlol????

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +            <div class="wrapper-for-content">
Эта обёртка для чего? для тега` p`?

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +    <main class="main-countent">
main-countent, во первых content, во вторых, зачем тут приставка main?

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                <div class="main-info"><span class="ifo-help">Оценка объема предстоящих работ</span><br><br> Стоимость переезда зависит от количества<br> комнат, вещей и мебели</p>
Что-то ты тут намудрил. давай по человечески сделай.

2021-04-27 08:11 UTC, DenisKalyanov commented on style/style.css
> +                position: absolute;
Опять ты этих абсолютов насовал. УДАЛИТЬ ВСЕ!

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                <div class="main-info"> <span class="ifo-help">Упаковка вещей</span><br><br> Упаковываем вещи в коробки, подписываем.<br> Габаритное и деликатное, упаковываем<br> отдельно.
Просто `span`

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                <p class="mobile-version-of-the-service1">Упаковка вещей</p>
**mobile-version-of-the-service1** что это за наименование классов?
Зачем ты туда абсолюты опять всунул?
ВООБЩЕ ИХ НИКОГДА НЕ ИСПОЛЬЗУЙ! Я запрещаю тебе их использовать.
Любые методы кроме абсолютов!

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                <span class="number-ico">03</span>
неправильное формирование блоков.

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +
что за провалы?

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +            <div class="main-info-two">
Зачем эта обёртка и для чего?
И где общий див для всего блока, а может и не `div` (отсылка к семантической вёрстке)

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                <div class="prices-box-two">
То что этот бокс второй, оно то понятно. Но стили то у них у всех одинаковые, тогда зачем создавать каждый раз новый класс?

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +            <div class="car-park-box">
Правильно дели блоки на странице. Если у тебя есть блок с автопарком, то почему ты его не выделил в отдельный БОЛЬШОЙ див?

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +        <section class="reviews">
а вот тут почему-то ты обернул блок с отзывами в отдельный section.

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                <div class="reviews-list">
Зачем лишняя обёртка? Эта ошибка повторяется на протяжении всех ПР, будь повнимательней, тут этот div не нужен вообще и смысла не несёт

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                        <p class="date-with-revocation">24.03.2019 ★★★★★</p>
а что будем делать когда рейтинг составит 4,5 звезды?
Или 4 звезды?  + звёзды по макету жёлтые.
Так вставлять не вариант.

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                <button class="btn-call-tariffs">Все отзывы</button>
Прошу внимательней читать ТЗ к заданиям. Там всё это было расписано.

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +
Что за пробелы?

2021-04-27 08:11 UTC, DenisKalyanov commented on style/style.css
> +                position: absolute;
Больше никаких абсолютов!
Любое решение кроме абсолютов во всей дальнейшей вёрстке.

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                        <a href="#" class="expand-review">Читать полностью</a>
А почему это ссылка?

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                    <div class="revocation-wrapper1">
revocation-wrapper1
revocation-wrapper2
revocation-wrapper3
revocation-wrapper100500
Так классы никто не именует. 
ПЛЮС ко всему, стили у всех этих классов одинаковые, тогда зачем плодить лишние классы?

2021-04-27 08:11 UTC, DenisKalyanov commented on index.html
> +                            что задерживается.<br> Когда.... </p>
`<br>` тут это не нужно, там просто перенос строки по тексту, он так попал

2021-04-27 08:20 UTC, Jaonja commented on index.html
> +                <p class="textlol">Как это происходит?</p>
это я забыл удалить) когда тестил верстку)

2021-04-27 08:22 UTC, Jaonja commented on index.html
> +                    <div class="revocation-wrapper1">
забыл переменовать ( тестил верстку )

2021-04-27 08:27 UTC, Jaonja commented on style/style.css
> +                position: absolute;
ну не, они иногда-редко но  нужны и тут он нужен) даже без выравнивания по стороне )

2021-04-27 08:49 UTC, Jaonja commented on index.html
> +            <div class="logo-car"> <img src="img/car.png" class="car-img" alt="img"></div>
блин реально не помню зачем я это делал, может тестил что-то и забыл удалить.

2021-04-27 08:49 UTC, Jaonja commented on index.html
> +    <main class="main-countent">
тут именно через u))

2021-04-27 08:50 UTC, Jaonja commented on index.html
> +                <div class="main-info"><span class="ifo-help">Оценка объема предстоящих работ</span><br><br> Стоимость переезда зависит от количества<br> комнат, вещей и мебели</p>
соглы.

2021-04-29 23:15 UTC, Jaonja commented on index.html
> +                <button class="btn-call-tariffs">Все отзывы</button>
Читать полностью? если так то исправил!

2021-04-30 12:30 UTC, itbgtk09 requested changes

2021-04-30 12:30 UTC, itbgtk09 commented on style/style.css
> +}
Необязательно использовать  ::before, чтобы сделать галочку,  у элементов списка есть свойство   list-style-image и list-style-position, чтобы не задавать padding.
Но и так тоже можно)

2021-04-30 12:44 UTC, e-bogatko requested changes

2021-04-30 12:44 UTC, itbgtk09 commented on style/style.css
> +}
У  тебя  выше по коду есть уже этот класс и там даже margin прописан, запихни туда этот margin и удали этот кусок кода

2021-04-30 12:44 UTC, itbgtk09 commented on style/style.css
> +        border-right: none;
border: none;
border-bottom: твоё значение

2021-04-30 12:44 UTC, itbgtk09 commented on style/style.css
> +        box-sizing: none;
box-sizing не имеет значение none, посмотри какие имеет значения и убедиться, что ты вообще правильно используешь это свойство

2021-04-30 12:44 UTC, itbgtk09 commented on style/style.css
> +    line-height: 24px;
px замени на rem

2021-04-30 12:44 UTC, itbgtk09 commented on style/style.css
> +    height: 17px;
px замени на rem

2021-05-03 06:26 UTC, DenisKalyanov requested changes

2021-05-03 06:26 UTC, DenisKalyanov commented on index.html
> +            <img src="img/Hum.png" class="human-img" alt="img">
зачем Hum  с большой буквы?

2021-05-03 06:26 UTC, DenisKalyanov commented on index.html
> +    <div class="service-header">
Это отдельный блок. Почему у него нет обёртки?

2021-05-03 06:26 UTC, DenisKalyanov commented on index.html
> +        <p class="prices">Цены</p>
```
<p class="prices">Цены</p>
<p class="prices-info">Фиксированная стоимость на переезд под ключ</p>
```

Зачем для этого отдельная обёртка? Оно идёт по очереди. Для всего блока должна быть одна большая обёртка, а в ней уже располагаться блоки. 
```
div class="wrepper"
      p class="prices"
      p class="prices-info"
      div class="main-container-forprices"
/div
```

2021-05-03 06:26 UTC, DenisKalyanov commented on index.html
> +            <p class="moving-information-time">Переезд за 6 часа</p>
```
moving-information-car
moving-information-employee
moving-information-time
```
Три разных класса с одинаковыми стилями.

2021-05-03 06:26 UTC, DenisKalyanov commented on index.html
> +            <p class="car-truck">Грузовики</p>
```
car-gazelle
car-heels
car-truck
```

Три разных класса с одинаковыми стилями.

2021-05-03 06:26 UTC, DenisKalyanov commented on index.html
> +                <div class="revocation-wrapper revocation-wrapper-mob-two">
`revocation-wrapper-mob-two` - тут он не нужен. Ты должен скрыть 1 и 3 отзывы, добавлением этого класса + ко всему не нужно придумывать разные им имена. у них будет одно общее свойство в мобильной версии и всё.
```
.revocation-wrapper-mob{
     display: none;
 }
```
А у второго блока ты убираешь этот класс и в мобильной версии изменяешь 
`.revocation-wrapper`

2021-05-03 06:26 UTC, DenisKalyanov commented on index.html
> +            <button class="btn-call-tariffs">Все отзывы</button>
`btn-call-tariffs` -- кнопка-вызова-тарифов?
Или лучше 
`all-reviews`  -- все-отзывы

2021-05-03 06:26 UTC, DenisKalyanov commented on style/style.css
> +    position: absolute;
Зачем тут абсолют?

2021-05-03 06:26 UTC, DenisKalyanov commented on style/style.css
> +        position: relative;
`position: relative;` ??

2021-05-03 06:26 UTC, DenisKalyanov commented on style/style.css
> +    .container-within-formation {
через 10 строк кода опять этот класс.

2021-05-03 09:40 UTC, Jaonja commented on index.html
> +    <div class="service-header">
это и есть обёртка) для блока

2021-05-03 09:41 UTC, Jaonja commented on index.html
> +        <p class="prices">Цены</p>
это обёртка для всего блока)

2021-05-03 10:29 UTC, DenisKalyanov approved these changes

2021-05-03 10:35 UTC, merged