Feature/ct 4
Jaonja/GitRepos pull request #13
Opened 2021-05-06 00:27 UTC by Jaonja

2021-05-06 08:16 UTC, DenisKalyanov requested changes

2021-05-06 08:16 UTC, DenisKalyanov commented on README.md
> +Учебный проект
В Ридми файле должно быть описание проекта. Напиши что за проект, о чём он, какие технологии используются, кто автор и т.д. 
Будет красиво)

2021-05-06 08:16 UTC, DenisKalyanov commented on index.html
> +            <h6>Закажи переезд прямо сейчас со скидной %</h6>
А чем ты руководствовался, что аж дошёл до `<h6>`? 
По сути это весомый заголовок, считай самый главный в этом блоке, так что его можно делать `h2`

2021-05-06 08:16 UTC, DenisKalyanov commented on index.html
> +            <h3 class="mobile-movee-order">Закажи переезд прямо сейчас</h3>
Это по сути тот же заголовок только для мобильной версии и ты решил там использовать `h6`, а тут `h3`

2021-05-06 08:16 UTC, DenisKalyanov commented on index.html
> +                </select>
выравнивание (форматирование кода)

2021-05-06 08:16 UTC, DenisKalyanov commented on index.html
> +            <h5 class="additional-services-text">Дополнительные услуги</h5>
Почему h5?

2021-05-06 08:16 UTC, DenisKalyanov commented on index.html
> +            <button class="btn-mobile-order">перезвонить</button>
Что-то в макете я не нашёл такой кнопки.

2021-05-06 08:16 UTC, DenisKalyanov commented on index.html
> +                <p class="footer-mobile-tex">Политика конфиденциальнности</p>
class="privacy" т.к. footer-mobile-tex - не даёт ни малейшего понятие о том, что же за текст будет в этом блоке.
Ты скажешь, что и так же видно что за текст, но вот тебе пример:
```
<p class="footer-mobile-tex"> {{tex}}</p>
<p class="footer-mobile-tex-two"> {{text}}</p>
<p class="footer-mobile-tex-three"> {{text}}</p>
<p class="footer-mobile-tex-four"> {{text}}</p>
```
Представим что в  {{text}} - приходят переменные с сервера и ты понятия не имеешь что там лежит, потому что писал этот код разработчик до тебя и теперь ты думаешь а где какой текст, а о чем вообще инфа в этих блоках и т.д.

Поэтому предлагаю назвать классы вот так, и сразу всё станет понятней.
```
class="privacy"
class="privacy-agree"
```

2021-05-06 08:16 UTC, DenisKalyanov commented on index.html
> +                </div>
зачем эта обёртка в виде `div`?

2021-05-06 08:16 UTC, DenisKalyanov commented on style/style.css
> +    .header {
Почему у тебя перезаливается весь файл с style.css? Мне приходится сейчас просмотреть 1500 строчек кода, чтобы найти ошибки.  Ты может добавил 50 строк кода, но я не знаю какие и мне сейчас нужно просмотреть 1500.

Что ты в нём изменяешь? 
И зачем у тебя 4 пробела перед всеми селекторами??

2021-05-06 08:16 UTC, DenisKalyanov commented on style/style.css
> +=======
что это за` =======`
Такой самодеятельности быть не должно оно сломает код.

2021-05-06 08:16 UTC, DenisKalyanov commented on style/style.css
>  /* header section */
удаляй все комментарии.

2021-05-06 08:16 UTC, DenisKalyanov commented on style/style.css
>  .header {
Немного непонятно, почему у тебя тег header идёт в самом конце стилей. По логике тут должен быть footer.

2021-05-06 10:10 UTC, Jaonja commented on style/style.css
>  .header {
Как-то странно, но у меня он у меня вначале кода

2021-05-06 10:10 UTC, Jaonja commented on style/style.css
>  /* header section */
это что бы найти где какой блок

2021-05-06 10:12 UTC, Jaonja commented on style/style.css
> +=======
странно у меня этого нету

2021-05-06 10:13 UTC, Jaonja commented on style/style.css
> +    .header {
про 4 пробелы, когда жму контр S (сохраняю) он автоматически ставит эти пробелы, аж горю от этого

2021-05-06 10:16 UTC, Jaonja commented on index.html
> +            <button class="btn-mobile-order">перезвонить</button>
это кнопка для мобильной "перезвонить (мне)"

2021-05-06 14:18 UTC, Jaonja commented on index.html
> +            <h5 class="additional-services-text">Дополнительные услуги</h5>
Исправил!)

2021-05-06 14:19 UTC, Jaonja commented on index.html
> +            <h6>Закажи переезд прямо сейчас со скидной %</h6>
косячный(

2021-05-07 11:19 UTC, DenisKalyanov requested changes

2021-05-07 11:19 UTC, DenisKalyanov commented on README.md
> +Сделан на Css. Html. JS
english pls

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                    <p class="payment-method">Способ оплаты</p>
Почему это тут?

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                        <span class="text">Наличными курьеру</span>
зачем тут 2 span?

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                        <span class="text">Банковский перевод</span>
тоже самое -//-

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                    <input class="cheabox-input" type="checkbox" id="cheackbox_1">
cheabox-input
checkbox

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                    <label class="cheackbox-label" for="cheackbox_1">Вызов замерщика</label>
cheabox-input
checkbox
cheackbox-label

Одно слово, но наизвращался ты над ним,  уже как мог

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                        <span class="choice-of-payment-method one" ></span>
input-radio-payment `two`
choice-of-payment-method `one`

Я тебе пишу в каждом ПР, что не именуй так классы.
Я бы понял если бы у тебя был список призёров олимпиады:

```
<li class="one" >1. Петя</li>
<li class="two" >2. Толя</li>
<li class="three" >3. Вася</li>
```
И то, нужно было бы добавлять one-place, two-place 

А у тебя, что значат классы one? two? Ничего не значат.

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                    <p class="specify-the-area">Укажите Город</p>
```
specify-the-area
location-select
```

Вот по сути у тебя 2 класса, несут они весьма похожий смысл, относятся к одному блоку, но по имени класса. можно сказать что они вообще из разных проектов.

```
set-location
select-location
```
например.

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                    <input class="add-city" type="text" required placeholder="Добавить город">
specify-the-area  `area`
location-select `location`
add-city `city`

Это всё один блок с городом, но ты решил использовать максимальное количество переменных имён, чтобы сбить грабителя со следа.

Если это всё связано с городом то:
```
set-city
select-city
add-city
```
or
```
city-set
city-select
city-add
```

2. Вторая часть вопроса
required - обозначает, что поле обязательно для заполнения. А если пользователь из Бреста, Брест уже есть, то что пользователю туда вообще заполнять? Это поля будет использоваться в том случае, если города откуда пользоатель, нет в предложенном ему списке

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                        <input type="radio" class="input-radio-payment there" name="name">
Ну если даже ты использовал one, two, то дальше должно было бы идти три, но there это далеко не три.
И не используй это. Зачем вообще тебе этот класс дополнительный?
```
input-radio-payment[checked]{
property: value;
}
```

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +            <button class="btn-mobile-order">перезвонить мне</button>
в макете точно с маленькой?

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                <input class="checkbox" type="checkbox" id="radio">
почему у него id="radio" ?

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +            <h1 class="mobile-movee-order">Закажи переезд прямо сейчас</h1>
`h1` ?
h1 должен быть только один на странице. 
Если ты его использовал в header, то больше никогда и нигде.

```
<h2>Закажи переезд прямо сейчас со скидной %</h2>
<h1 class="mobile-movee-order">Закажи переезд прямо сейчас</h1>
```

Это же один и тот же текст (блок) по сути, просто один в дестоп, другой в мобильной. Тогда почему у них разные теги?

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                <input class="make-order name" type="text" required placeholder="Ваше имя">
make-order переводиться как "Сделать-заказ"
В этой графе у на инфа о пользователе.
**user-data** or **user-info**

И если стилизация блоков одинаковая, то нужен ли тут доп. класc в виде name u tel

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                        <input type="radio" class="input-radio-payment two" name="name">
name="name" ?
class="class"
id='id"

имя=имя ??
Текст в ковычках должен нести смысловую нагрузку. Это же имя! аргумент говорит сам за себя, он этот тег прямо ждал, что ему дадут красивое имя и ему не будет стыдно перед одноклассниками, а тут его создатель не заморачивался. Когда ему стукнет 18 он явно пойдёт в паспортный стол, чтобы сменить имя, но может не будем ломать этому тегу жизнь?

2021-05-07 11:19 UTC, DenisKalyanov commented on index.html
> +                    <input class="cheabox-input" type="checkbox" id="cheackbox_2">
id="cheackbox_2"
 Смотри, после в JAVASCRIPT тебе возможно прийдётся обрабатывать эти теги по id
 querySelectorById, ты создашь там 10 переменных
```
let 1 = cheackbox_1
let 2 = cheackbox_2
let 3 = cheackbox_3
let 4 = cheackbox_4
```
Удобно ли тебе будет взаимодействовать и этим кодом?
Будешь ли ты понимать в каком чекбоксе какая информация приходит? Да хрен тут разберёшь что в каждом из них. Этим ты неимоверно усложняешь себе жизнь. Сейчас вроде легко проименовал, но потом это будут адские муки.

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +/* order block*/
/* order block*/
А нужен ли тут этот комментарий?

Код должен быть написан так, чтобы комментарии были не нужны.
Так же и наименование классов. Если их именовать one, two, name=name
То в таком коде конечно, без комментариев не разобраться. А если давать классам адекватные и понятные имена, то и комментарии не нужны будут, суть будет понятна издалека.

Поэтому комментарий в коде быть не должно. Удаляем!

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +.we-will-call-you-back {
we-will-call-you-back 
какое ужасное название класса. 
Можно покороче?*

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +.text {
что за класс?
Что за text?  К чему он относиться? Ну не понять же никогда в жизни, он может быть в любом блоке и в любой строчке кода. Не информативный класс, никто никогда в жизни не поймёт что за текст там внутри и почему он relative

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +    transform: .2s;
0.2s

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +.text {}
`.text {}`

Что это такое?
Ох уж этот text

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +.chekbox-okey {
chekbox-okey 
**okey** ????

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +    opacity: 2;
opacity откуда ты узнал о таком свойстве в css?
Если ты где-то его нашёл, то там пишет, что он может принимать значения от 0 до 1

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +        display: none;
а чё, а как звонить дальше? А как заказать обратный звонок?
Если у человека экран не 4К то ему не будет доступная такая кнопка?

Ну а что ж он, нищеброд, не заслужил))

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +        opacity: 50%;
Не знаю работает или нет. Но знаю
https://developer.mozilla.org/ru/docs/Web/CSS/opacity

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +@media (max-width: 496px) {
нужно загуглить, какие есть разрешения экранов у телефонов.
Если мене не изменяет память. то мобилы начинаются с 480, тогда смысл делать разрешение на 16 пикселей больше. Если дальше идут мобилки и надо делать уже лучше под мобилу.

Но я могу и ошибаться, возможно есть мобилки с 496px шириной))

2021-05-07 11:19 UTC, DenisKalyanov commented on style/style.css
> +    margin-bottom: 2.5rem;
на 937 строке тот же код

2021-05-07 11:31 UTC, Jaonja commented on index.html
> +                        <span class="text">Наличными курьеру</span>
мне так Фантамас с видео сказал)))

2021-05-07 11:37 UTC, Jaonja commented on style/style.css
> +    opacity: 2;
Я где-то читал, для картинки опасити чем больше, тем она прозрачнее

2021-05-12 11:22 UTC, DenisKalyanov requested changes

2021-05-12 11:22 UTC, DenisKalyanov commented on index.html
> +                        <p class="payment-method">Способ оплаты</p>
why is it here?

2021-05-12 11:22 UTC, DenisKalyanov commented on index.html
> +                        <label class="payment-">
class="payment-"

2021-05-12 11:22 UTC, DenisKalyanov commented on index.html
> +                    </label>
FORMATTING THE CODE!

2021-05-12 11:22 UTC, DenisKalyanov commented on index.html
> +                        <input class="additional-services-checkbox" type="checkbox" id="cheackbox_crane">
cheackbox
or
checkbox
Maybe you need install ESLint, which will checked you gramma. Read about it.

2021-05-12 11:22 UTC, DenisKalyanov commented on index.html
> +                    <label class="checkbox-cheack" for="data-processing">Даю согласие на обработку данных</label>
**cheack**
use google translate, if you have problem with english, but don't use misspelled words

2021-05-12 11:22 UTC, DenisKalyanov commented on index.html
> +            <div class="footer-nav-list">
This is an redundant wrapper. Why is this here? What's the logic in using this div?

2021-05-12 11:22 UTC, DenisKalyanov commented on style/style.css
> +        display: none;
Это я к тому, что кнопка должна пропасть только на мобиле)

2021-05-12 11:22 UTC, DenisKalyanov commented on style/style.css
> +    }
You added 1000 line of  css code in last part project.  Realy?))

2021-05-12 11:22 UTC, DenisKalyanov commented on style/style.css
> +/*footer*/
Why you again using comments in your code? 
I said you to delete its.

2021-05-12 11:22 UTC, DenisKalyanov commented on style/style.css
> +/* checkbox additional-services-wrapper*/
delete comments.

2021-05-12 11:22 UTC, DenisKalyanov commented on style/style.css
> +/* radio-method-box*/
We don't use comments in the code. I already talked about this, why aren't you listening to me?

2021-05-12 11:22 UTC, DenisKalyanov commented on index.html
> +                    <div class="button-btn-order">
button-btn-order
what does btn mean? I thought it was a button.

2021-05-12 11:39 UTC, Jaonja commented on style/style.css
> +        display: none;
ааааааааааааааааааааааааа понялллллллллл

2021-05-12 11:44 UTC, Jaonja commented on index.html
> +                        <p class="payment-method">Способ оплаты</p>
вроде так и должно быть)

2021-05-12 11:46 UTC, Jaonja commented on index.html
> +                        <label class="payment-">
исправил

2021-05-12 11:47 UTC, Jaonja commented on index.html
> +                        <label class="payment-">
испрвил

2021-05-12 11:59 UTC, Jaonja commented on index.html
> +                    <div class="button-btn-order">
действительно))))

2021-05-13 06:24 UTC, DenisKalyanov requested changes

2021-05-13 06:24 UTC, DenisKalyanov commented on style/style.css
> +}
к чему относится эта скобка?

2021-05-13 10:05 UTC, DenisKalyanov requested changes

2021-05-13 10:05 UTC, DenisKalyanov commented on index.html
> +                        <select class="city-select" name="">
name="" или заполняем атрибут или убираем его.

2021-05-13 10:05 UTC, DenisKalyanov commented on index.html
> +                        <option value="1">Мозырь</option>
Отформатируй код. 
Ну не видно же вложенности, всё в одну колонку идёт.
Перед отправкой кода на ПР воспользуйся Prettier.

Почему вверху код отформатирован в теге select, а тут нет?

2021-05-13 10:05 UTC, DenisKalyanov commented on style/style.css
> +.additional-services-text {
Чуть выше ты уже указал этот класс. И тут опять его дублируешь. 
Код должен быть маленьким, а не разрастаться.
Строка 537

2021-05-13 10:05 UTC, DenisKalyanov commented on style/style.css
> +.order-box {
Опять дублируешь тот же класс. 
Смотри 523 строку.
ПЕРЕСМОТРИ ВСЕ СТРОКИ КОДА! 
Не должно быть так, что класс повторяется через 10 строчек кода. Поэтому у тебя и css файл на 1500 строк.
Если я оставляю подобный комментарий в одном месте с повторением классов, ты должен проверить весь CSS, чтобы избавиться от данного косяка, а не только в том месте где я оставил комментарий.

2021-05-13 10:05 UTC, DenisKalyanov commented on index.html
> +                        <input type="radio" class="input-radio-payment" name="radio-bank-transfer">
Если тег вложен в другой тег, то он должен быть после отформатирования расположен правее этого тега.
Как я и показывал на скрине.

2021-05-13 10:19 UTC, DenisKalyanov requested changes

2021-05-13 10:19 UTC, DenisKalyanov commented on index.html
> +                    <a href="#header" target="_blank">
href="#header" зачем?

2021-05-13 10:19 UTC, DenisKalyanov commented on index.html
> +                        <img src="img/faceBig.png" alt=" ">
В будущем, лучше использовать svg.

2021-05-13 10:19 UTC, DenisKalyanov commented on style/style.css
> +.input-radio-payment {
Что за input-radio-payment на 652 строке с отступами. Зачем он если тут этот класс display: none;
Почему ты так относишься к своему коду? совсем не следишь за ним. 

Если ты хочешь чуму-то научиться, тогда прикладывай максимум усилий, чтобы сделать код лучше, чище, меньше. А не накидывать сюда всё подряд.

2021-05-13 10:19 UTC, DenisKalyanov commented on style/style.css
> +    appearance: none;
а зачем это тут? Сам об этом свойстве мало знаю, точно ли оно помогло тебе скрыть чекбокс?

2021-05-13 10:19 UTC, DenisKalyanov commented on style/style.css
> +.shadow-btn-order {
Несколькими строчками выше он у тебя position: absolute;
Проверь все классы, чтобы не было повторений. 
Потому что ты сам перезаписываешь стили, сам того не понимая и твоя вёрстка будет вести себя так, как ты даже не подозреваешь.

2021-05-13 10:33 UTC, Jaonja commented on index.html
> +                    <a href="#header" target="_blank">
Хотел сделать что бы при клике, на кнопку открывался нужный мне раздел. но почему-то не вышло.(

2021-05-13 10:36 UTC, Jaonja commented on index.html
> +                    <a href="#header" target="_blank">
<li><a href="" target="_blank">Главная</a> </li>
                <li><a href="" target="_blank">Цена</a></li>
                <li><a href="" target="_blank">Автопарк</a></li>
                <li><a href="" target="_blank">Отзывы</a></li>
                <li><a href="" target="_blank">Контакты</a></li> вот тут хотел сделать и тестировал на похожих элементах

2021-05-13 10:47 UTC, Jaonja commented on style/style.css
> +    appearance: none;
Конечно помогло)))

2021-05-14 08:39 UTC, DenisKalyanov requested changes

2021-05-14 08:39 UTC, DenisKalyanov commented on index.html
> +              <img src="img/truck.png" alt="img" /><span class="info-list">Более 800<br />переездов</span> <img src="img/box.png" alt="img" /><span class="info-list">Бережная<br />упаковка</span> <im
1. что должно быть расположено в alt ?
2. Что это за строка длиною в жизнь!?

2021-05-14 08:39 UTC, DenisKalyanov commented on index.html
> +          <img src="img/gazell.png" alt="img" class="gazel-info-mobil" />
так же по поводу содержимого **alt**

2021-05-14 08:39 UTC, DenisKalyanov commented on index.html
> +        <h5 class="сustomer-кeviews">Отзывы</h5>
По сути это очень важный заголовок, так как он описывает целый раздел.
Ему можно дать и **h2**

2021-05-14 08:39 UTC, DenisKalyanov commented on index.html
> +          </div>
```
<div class="revocation-wrapper revocation-wrapper-mob">
            <p class="user-feedback">Ольга Петровна</p>
            <p class="date-with-revocation">24.03.2019</p>
            <p>Могу на ...</p>
            <span class="expand-review">Читать полностью</span>
```
Ты говоришь тебе трудно именовать классы. Конечно выдумывая такие имена, что чёрт ногу сломит.

Ты сам себя путаешь, называя классы то с аббревиатурой `feedback`, потом `revocation` и `review` потом ещё удлиняешь название. Ты на ровном месте сам себе усложняешь максимально жизнь. Почему не сделать максимально просто:

```
<div class="feedback-wrapper feedback-wrapper-mob">
            <p class="feedback-user">Ольга Петровна</p>
            <p class="feedback-date">24.03.2019</p>
            <p>Могу на ...</p>
            <span class="feedback-full">Читать полностью</span>
```

![palka-768x359](https://user-images.githubusercontent.com/57324793/118240630-e768b500-b4a3-11eb-8e46-e82bf2eda7d0.jpg)

2021-05-14 08:39 UTC, DenisKalyanov commented on index.html
> +        <div class="payment-method-box">
`payment-method-box` ещё один твой косяк в наименовании классов.
Ты сам себе усложняешь жизнь и процесс разработки тем, что именуешь классы так, как буд-то забыл как именовал похожие блоки до этого.

Если ты используешь для обёртки в имени класса аббревиатуру box, то используй её на всём проекте. Но если используешь wrapper для именования обёрток, то продолжай с wrapper. Ты же можешь максимально всё упростить, но всё сам максимально усложняешь. 

Ты вообще мог бы сразу визуально разбить свой проект на несколько wrappers, просто с разными префиксами.
Типо header-wrapper, main-wrapper, feedback-wrapper и так далее...

Но тут я хочу акцентировать внимание, что ты нагружаешь себя лишней работой и свой мозг даже в том случае, когда думаешь что использовать в названии класса wrapper или box. Используй всегда wrapper и уже голова будет меньше запарена.

2021-05-14 08:39 UTC, DenisKalyanov commented on index.html
> +              Банковский перевод
Ты же говорил, что всё проверил и всё соответствует макету. Но как ты не заметил что у тебя:
2 "Банковских перевода"

2021-05-14 08:39 UTC, DenisKalyanov commented on index.html
> +          <div class="additional-services-item">
```
<div class="additional-services-wrapper">
    <div class="additional-services-item">
```
Пример как можно сократить наименование классов:
```
<div class="additional-services">
    <div class="additional-service">
```
Что я тут сделал, убрал **wrapper** и **item**.
Что я сделал ещё? В первом блоке обёртке наименование в **множественном** числе. а во втором случае **один**, без окончания **s**

2021-05-14 08:39 UTC, DenisKalyanov commented on index.html
> +        <div class="time-button-wrapper">
`div class="time-button-wrapper"`
Ну название конкретное ГЭ...
Ну а если в блоке будет время, кнопка, форма, input, и сайдер
`div class="time-button-form-input-slider-wrapper"` ?? И так сойдёт?
Садишь и думаешь, что это за блок. БЛОК ЗАКАЗАТЬ СО СКИДКОЙ, значит discount-time
``div class="discount-time"`

2021-05-14 08:39 UTC, DenisKalyanov commented on index.html
> +        <div class="box-in-the-card">
Садишься, чешешь затылок и понимаешь, что в этом блоке контакты! Эврика!
А ты как назвал? `box-in-the-card` бокс-в-карточке

2021-05-14 09:50 UTC, Jaonja commented on index.html
> +        <div class="payment-method-box">
Хорошо.)

2021-05-14 09:52 UTC, Jaonja commented on index.html
> +        <div class="payment-method-box">
Оставлю пока как есть.

2021-05-14 10:01 UTC, Jaonja commented on index.html
> +          <img src="img/gazell.png" alt="img" class="gazel-info-mobil" />
текстовое описание содержимого)

2021-05-14 10:02 UTC, Jaonja commented on index.html
> +              <img src="img/truck.png" alt="img" /><span class="info-list">Более 800<br />переездов</span> <img src="img/box.png" alt="img" /><span class="info-list">Бережная<br />упаковка</span> <im
та это форматер ее так перенёс строку

2021-05-14 10:12 UTC, Jaonja commented on index.html
> +        <div class="box-in-the-card">
не знаю ,сделал ли название лучше сейчас, но думал минут 15 именно над этим ))
назвал его "бокс с контактами" вроде информативно и понятно что в нем находится.

2021-05-14 14:13 UTC, merged