Feature/ct 5
Jaonja/GitRepos pull request #14
Opened 2021-05-18 16:20 UTC by Jaonja

2021-05-19 09:03 UTC, DenisKalyanov requested changes

2021-05-19 09:03 UTC, DenisKalyanov commented on reset.css/reset.css
> +}
Ты смотришь что каждый раз добавляешь на гит?
Почему у тебя опять добавлен весь этот код?

2021-05-19 09:03 UTC, DenisKalyanov commented on index.html
> +</html>
Тоже весь код зачем перезалил? Мне что смотреть то? git специально для того, чтобы я отслеживал последние изменения и не возвращался к старым. Потому что там уже все видел.

2021-05-19 09:03 UTC, DenisKalyanov commented on script/additional-servicesHide.js
> +    this.style.display = "none"
сделай через toggle, Добавить/удалить класс. Ты сейчас это вручную делаешь, а можешь сделать, что при нажатии на кливишу один клас удаляется, другой добавляется.
Ещё раз нажал на клаившу, опять сработала та же функция но toggle поменял класс на противоположный.

2021-05-19 09:03 UTC, DenisKalyanov commented on script/slider.js
> +    $truck.style.borderColor = "#EBEBEB"
зачем ты тут добавляешь стили? Я же по моему должен был указывать в ТЗ, что стили максимально используем в CSS, в JS только в случаях обстрой необходимости и безвыходности. А ты вообще borderColor добавляешь с помощью JS, зачем!?
Это относиться ко всему коду

2021-05-19 09:03 UTC, DenisKalyanov commented on style/style.css
> +.header {
Предлагаешь мне опять перепроверить 1533 строчки кода?
Не знаю зачем ты это сделал и всё опять перезалил

2021-05-19 09:03 UTC, DenisKalyanov commented on script/timer.js
> +let timer_life = 20245 //секунды в минутах и часах
Лучше делать максимально открыто. Чтобы можно былопонять о чем речь. Например 1 день:
24 * 60 * 60 *1000
24 часа * кол-во минут в час * кол-во сек * 1000 милисекунд. Наглядно понятно.
А так у тебя с 1го раза и не скажешь сколько времени

2021-05-19 09:03 UTC, DenisKalyanov commented on script/timer.js
> +  timer_life -= 1
И ещё в наименовани используем camelCase

2021-05-19 09:03 UTC, DenisKalyanov commented on script/slider.js
> +console.log ($boxHeel)
В ПР console.log быть не должно! Если сейчас ты об этом не знал, то в дальнейшем оправдания, что забыл удалить не прокатят )

2021-05-19 09:03 UTC, DenisKalyanov commented on script/slider.js
> +     $heel.style.borderColor = "#EBEBEB"
Смотри у тебя 3 части одинакового кода. Попробуй воспользооватся циклами. Например for, для переборки твоего кода. Возможно нужно будет поменять наименования классов. Перебирать по классу.
Например при нажатии кнопка "ГАЗЕЛЬ" Мы должны перебрать массив наших элементов и скрыть все id которых не равен $gazel = document.querySelector("#gazel"). Это будет 1 функция, универсальная.

2021-05-19 09:03 UTC, DenisKalyanov commented on script/additional-servicesHide.js
> +
замысел в том, что #hideBox" и  "#upBox" это одна и та же кнопка. Просто по нажатию она переворачивается.
Так же будет работать если ты напишешь `let $upBox = document.querySelector("upBox")` без #

2021-05-19 09:03 UTC, DenisKalyanov commented on script/timer.js
> +    w = w < 10 ? "0" + w : w
что такое w?
Именнуй переменные правильно и понятно.

2021-05-19 09:03 UTC, DenisKalyanov commented on script/timer.js
> +  if (timer_life == 0) {
Привыкай всегда использовать строгое сравнение типов

2021-05-19 09:03 UTC, DenisKalyanov commented on script/timer.js
> +    s = s < 10 ? "0" + s : s
Три одинаковые по смыслу функции. может как-то можно из объеденить?

2021-05-19 10:09 UTC, Jaonja commented on script/slider.js
> +     $heel.style.borderColor = "#EBEBEB"
Я думал об этом

2021-05-28 09:48 UTC, DenisKalyanov requested changes

2021-05-28 09:48 UTC, DenisKalyanov commented on script/additional-servicesHide.js
> +   if ($additionalServicesHide.classList.toggle('up')) {
Что тебе возвращает classList.toggle?

2021-05-28 09:48 UTC, DenisKalyanov commented on script/slider.js
> +    if ($boxHeel.classList.add('hide') === $boxHeel.classList.add('hide')){
как работает и что тебе возвращает вообще classList.add ?
Ты вообще понимаешь что написал в этой строке?)

2021-05-28 09:48 UTC, DenisKalyanov commented on script/validator.js
> +  };
я на созвоне во вторник спрошу у тебя как работает эта функция

2021-05-28 10:04 UTC, Jaonja commented on script/slider.js
> +    if ($boxHeel.classList.add('hide') === $boxHeel.classList.add('hide')){
Я Переделал уже

2021-06-09 12:12 UTC, DenisKalyanov requested changes

2021-06-09 12:12 UTC, DenisKalyanov commented on script/validator.js
> +  phoneInput.classList.remove("iValid");
invalid

2021-06-09 12:12 UTC, DenisKalyanov commented on script/slider.js
> +  Width = document.querySelector(".slider ").offsetWidth;
ты решил изменить название with на Width....

2021-06-09 12:21 UTC, merged