Feature/ct 2
Jaonja/GitRepos pull request #6
Opened 2021-04-13 20:42 UTC by Jaonja

2021-04-13 20:42 UTC, Jaonja commented
s

2021-04-14 08:54 UTC, DenisKalyanov requested changes

2021-04-14 08:54 UTC, DenisKalyanov commented on reset.css/reset.css
> +  margin: 0;
замени все эти теги просто `*`

2021-04-14 08:54 UTC, DenisKalyanov commented on reset.css/reset.css
> +:focus {
к чему применяется этот focus?

2021-04-14 08:54 UTC, DenisKalyanov commented on reset.css/reset.css
> +	display: block;
Эти теги и так блочные.

2021-04-14 08:54 UTC, DenisKalyanov commented on reset.css/reset.css
> +    color: #222;
У нас в проекте нет такого цвета.

2021-04-14 08:54 UTC, DenisKalyanov commented on reset.css/reset.css
> +@media (max-width: 320px) {
Документ reset.css служит для обнуления каких-то стилей и прочего. А ты тут уже начал наши классы прописывать.

2021-04-14 08:54 UTC, DenisKalyanov commented on index.html
> +                <button id="btn">заказать</button>
id мы не используем для стилизации кнопок.

2021-04-14 08:54 UTC, DenisKalyanov commented on index.html
> +                <div class="nav-header-list"><a href="tel:8(029)-999-12-13">8(029)-999-12-13</a></div>
Класс nav-header-list подрузамевает, что у тебя тут лежит какой-то список из заголовка. А тут просто телефон.

2021-04-14 08:54 UTC, DenisKalyanov commented on index.html
> +                        <img src="img/MOVEE.png" alt="img" class="header_logo-pic">
Зачем такая большая вложенность. 
`div`, в нём `a`, дальше `img`

2021-04-14 08:54 UTC, DenisKalyanov commented on index.html
> +                <div class="logo-logo-test"> <img src="img/car.png" class="man-car" alt="img"></div>
logo-logo ?

2021-04-14 08:54 UTC, DenisKalyanov commented on style.css
> +.body {}
Что это за пустой файл? удаляй.

2021-04-14 08:54 UTC, DenisKalyanov commented on style/style.css
> +}
почему код начинается со скобки?

2021-04-14 08:54 UTC, DenisKalyanov commented on index.html
> +                    <img src="img/Ellipse2.png" alt="img" class="phone-eclipse-two">
Я ж в ТЗ указал как это делается. Совсем не так.

2021-04-14 08:54 UTC, DenisKalyanov commented on index.html
> +            <div class="header_wrapper">
Что значит это нижнее подчеркивание в имени класса?

2021-04-14 08:54 UTC, DenisKalyanov commented on index.html
> +                        <li class="header-item"><a href="#!" class="header-link">Цены</a> </li>
header-item
header-link

Не информативное название классов. О чём они говорят? Если ты их обернул в nav, значит это уже ссылка навигации и т.д.

2021-04-14 10:00 UTC, Jaonja commented on index.html
> +                    <img src="img/Ellipse2.png" alt="img" class="phone-eclipse-two">
а как это сделать не совсем понятно

2021-04-14 10:01 UTC, Jaonja commented on index.html
> +                    <img src="img/Ellipse2.png" alt="img" class="phone-eclipse-two">
создать голубой див? с бордер радиусом 100%?

2021-04-15 08:06 UTC, DenisKalyanov requested changes

2021-04-15 08:06 UTC, DenisKalyanov commented on index.html
> +                        <li class="header-nav-list"><a href="#!" class="nav-link">Цены</a> </li>
list это список.
делаешь 
```
ul header-nav-list
li header-nav-item
```

2021-04-15 08:06 UTC, DenisKalyanov commented on index.html
> +                <div class="nav-header-phone"><a href="tel:8(029)-999-12-13">8(029)-999-12-13</a></div>
`nav-header-phone` до этого имя класса начиналось с `header-nav...`
и `nav` значит что это навигация по сайту (меню) телефон не относиться к навигации, он у тебя даже в тег `nav`  попал.

2021-04-15 08:06 UTC, DenisKalyanov commented on index.html
> +                <h3 id="title-style">По Бресту и области</h3>
id="title-style" зачем id??
Мы стилизуем только по классам. 
И опять пляшет наименование стилей.
```
<h2 class="inrto-title"
 <h3 id="title-style"
```
Сначала titel в начале, потом в конце.

2021-04-15 08:06 UTC, DenisKalyanov commented on index.html
> +                    </div>
Для начала это должно нажиматься и будет идти вызов.
Во вторых это делается как
```
<div>
   <a></a>
</div>
```
Картинку вставляем через before или after.

2021-04-15 08:06 UTC, DenisKalyanov commented on index.html
> +                    <img src="img/truck.png" class="img-container" alt="img"><span class="info-list">Более 800<br>переездов</span>
`class="img-container"`
Что под собой подразумевает слово container? То что это для хранение чего-то или в него будет что-то вкладываться, например:

```
<div class="img-container">
   <img></img>
   <img></img>
   <img></img>
</div>
```

 Тут `div` служит контейнером для многих `img`, а у тебя?

2021-04-15 08:06 UTC, DenisKalyanov commented on index.html
> +                        <div class="phone-img"></div>
в строчный тег `а` ты вкладываешь блочный тег `div`

2021-04-15 08:06 UTC, DenisKalyanov commented on index.html
> +                <div class="logo-img"> <img src="img/Hum.png" class="human" alt="img"></div>
class="logo-img" это же не логотип. Почему тогда класс с лого?

2021-04-15 08:06 UTC, DenisKalyanov commented on style/style.css
> +.Move-nav {
наименование или всё с маленькой или всё с большой. Придерживаемся одного стиля.

2021-04-15 08:06 UTC, DenisKalyanov commented on style/style.css
> +    position: absolute;
Почему так много absolute?
При просмотре фигмы, я вижу их ну штучки 4, а тут насчитал 8 штук.

2021-04-15 08:06 UTC, DenisKalyanov commented on style/style.css
> +.list-info {
Что-то я такого класса не нашёл в HTML

2021-04-15 08:06 UTC, DenisKalyanov commented on index.html
> +                <div class="logo-img"> <img src="img/car.png" class="man-car" alt="img"></div>
man-car, по моему там просто картинка.

2021-04-15 11:29 UTC, Jaonja commented on index.html
> +                <div class="nav-header-phone"><a href="tel:8(029)-999-12-13">8(029)-999-12-13</a></div>
Орнул с коммента) да уж реально к чему тут навигаций

2021-04-19 09:09 UTC, DenisKalyanov requested changes

2021-04-19 09:09 UTC, DenisKalyanov commented on style/style.css
> +        display: none;
Вверху 2 класса сгрупировал, а этот чего не добавил?

2021-04-19 09:11 UTC, DenisKalyanov requested changes

2021-04-19 09:11 UTC, DenisKalyanov commented on style/style.css
> +    max-width: 120rem;
А если у меня будет разрешение экрана 4к, то что мне контент не растянется даже? 
Пожалел пространство для контента?

2021-04-19 12:27 UTC, closed without merging